# Generated by Django 5.0.6 on 2024-07-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(default='img.jpg', upload_to='image/%Y', verbose_name='Изображение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(verbose_name='Дата публикации'),
        ),
    ]
