# Generated by Django 5.0.6 on 2024-07-07 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_main', '0004_comments_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100, verbose_name='IP-address')),
                ('pos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_main.post', verbose_name='Публикация')),
            ],
        ),
    ]
